# Claude Orchestration - Production Configuration

orchestrator:
  agents:
    maxAgents: 20
    defaultTimeout: 300000
    retryAttempts: 3
    healthCheckInterval: 60000
  
  patterns:
    swarm:
      enabled: true
      maxConcurrency: 20
      resultAggregation: consensus
    
    pipeline:
      enabled: true
      stageTimeout: 180000
      failureHandling: stop
    
    consensus:
      enabled: true
      minAgreement: 0.8
      maxRounds: 10
    
    mapreduce:
      enabled: true
      chunkSize: 1000
      reduceStrategy: merge
  
  monitoring:
    enabled: true
    port: 3000
    metricsRetention: 604800000
    logLevel: warn
    exportInterval: 60000
  
  memory:
    enabled: true
    maxEntries: 100000
    compressionEnabled: true
    indexingEnabled: true
    cacheSize: 10000

claude:
  subscription:
    mode: subscription
    maxTokens: 8192
    temperature: 0.5
    rateLimitRpm: 200
  
  fallback:
    enabled: true
    providers: []
    timeout: 60000

security:
  authentication:
    enabled: true
    provider: oauth
    sessionTimeout: 1800000
  
  authorization:
    enabled: true
    defaultRole: user
  
  encryption:
    enabled: true
    algorithm: aes-256-gcm
    keyRotationInterval: 604800000

storage:
  type: mongodb
  path: /var/lib/claude-orchestrator
  backup:
    enabled: true
    interval: 21600000
    retention: 30

features:
  experimental:
    asyncPatterns: false
    aiOptimization: false
    distributedExecution: false
    advancedMemory: false
  
  beta:
    webInterface: true
    restApi: true
    realTimeUpdates: true
    metricsExport: true
  
  stable:
    cliInterface: true
    configurationManagement: true
    basicMonitoring: true
    memoryPersistence: true

performance:
  cpu:
    maxCpuUsage: 80
    throttleThreshold: 90
  
  memory:
    maxMemoryUsage: 2147483648  # 2GB
    gcInterval: 300000
  
  network:
    maxConnections: 5000
    connectionTimeout: 30000
    keepAliveTimeout: 5000
  
  cache:
    maxCacheSize: 268435456  # 256MB
    ttl: 3600000
    compressionEnabled: true